# Site settings
name: actor
email: circle790@163.com
author: actor
url: "https://circle790.github.io"
resume_site: 
github: "https://github.com/circle790"
baseurl: 
description: 人生因为相遇而充满色彩，在隐忍中奋斗，在孤独中跋涉，用坚实的脚步慢慢靠近远方的憧憬，我们都是自己命运的演绎者。
meta_description: actor;闫圆;个人博客;活到老;学到老;生命不止;折腾不休;
motto: Make a big smile everyday!
banner: Being friendly is a courteous convention!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: circle790

highlighter: rouge
# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : circle790
